### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by Nekonaro** [NovaEngineering-Source/StellarCore#10]
If I want to enable the WipeModelCache feature, do I need to disable anything specific in VintageFix?
AlwaysDeferChunkUpdates feature and [Vintagium](https://github.com/Asek3/sodium-1.12) mod?

**Comment by KasumiNova** [comment]
`WipeModelCache` is automatically disabled when VintageFix's `DynamicResources` feature is enabled.
`AlwaysDeferChunkUpdates` is also automatically disabled when Vintagium is installed.
It doesn't affect the game, but you can manually disable both of these features.
