### ISSUE TITLE
[Feature Request - Techguns]

### ISSUE THREAD

**Issue by Sereath** [NovaEngineering-Source/StellarCore#11]
Hello again,

I was wondering if it would be feasible to fix these server-related crashes. Since you are the only developer to have addressed Techguns with your mod.
They're not common, so they're hard to replicate, but they're very bad crashes, because they'll keep crashing the server until the chunk with the player or entity using those weapons is deleted.

It all seems to be related to client stuff being forced in a server, happens a lot more often with the Flamethrower and the Biogun:

-
Triggered by a player on a server using a Flamethrower:
https://gist.github.com/Sereath/b7a2f713be9e45eb5784e2821b29884c

-
Triggered by an Outcast mob using a Flamethrower as well:
https://gist.github.com/Sereath/68f8f1c015eccd07cbb69e307f316cfd
https://gist.github.com/Sereath/16e0378f36581c3a93532294e029e0b3

-
And these are triggered by Outcast mobs using Bioguns:
https://gist.github.com/Sereath/e410f439bb312d4f6e2435f9f4008855
https://gist.github.com/Sereath/aa9d892ced768af126a19b0160af1aee
https://gist.github.com/Sereath/47198993f680ce7d52cbb65bc229d0cc

We would really appreciate it if something could be done about this as the original Techguns developer is no longer updating their mod, not even accepting Pull Requests nor forks. 
Thanks again for your time.

**Comment by KasumiNova** [comment]
🤔A fix was commited, but since I can't reproduce the issue, I may need you to test it, download it in Actions.

**Comment by Sereath** [comment]
I'll test it with a local server as soon as I can, as it is indeed difficult to reproduce. Thank you.

**Comment by Sereath** [comment]
I'll be doing tests now. Got a copy of a server crashing.

**Comment by Sereath** [comment]
It works. Tried it on two different servers.

Thank you very much. Everything should be good.
