### ISSUE TITLE
Zip file StellarCore-1.3.4.jar failed to read properly, it will be ignored（模组载入失败）

### ISSUE THREAD

**Issue by Cnzw** [NovaEngineering-Source/StellarCore#12]
# 环境
Windows Server 2016
JVM: DragonWell 8
CatServer-5a600445-universal（1.12）
StellarCore-1.3.4

# 日志
https://mclo.gs/9isP9hM

关键日志：https://mclo.gs/9isP9hM#L228

**Comment by KasumiNova** [comment]
RFG 自动生成的 Class 的问题，不影响游戏运行。
