### ISSUE TITLE
星核1.4.15给botania的饰品的饰品属性给创掉了

### ISSUE THREAD

**Issue by touhouzun** [NovaEngineering-Source/StellarCore#13]
https://www.curseforge.com/minecraft/mc-mods/stellarcore/files/5772668
星核1.4.15给botania的饰品的饰品属性给创掉了，导致原本的磁力戒指等所有botania的饰品无法装备
Electroblob's Wizardry的饰品属性是正常的
回退到1.3.4恢复正常

**Comment by KasumiNova** [comment]
哪里发布的 1.4.15？

**Comment by touhouzun** [comment]
> 哪里发布的 1.4.15？

https://www.curseforge.com/minecraft/mc-mods/stellarcore/files/5772668

**Comment by KasumiNova** [comment]
提供一份日志。

**Comment by touhouzun** [comment]
> 提供一份日志。

https://gist.github.com/touhouzun/43bda2226c4f3b2cee2d9a2ba8ba4213
![2024-10-01_16 21 51](https://github.com/user-attachments/assets/f6c4fa6f-ffa4-4cba-b73b-36da154a0dbf)
![2024-10-01_16 22 19](https://github.com/user-attachments/assets/ee1d1d74-c352-47ad-999d-00ec5b3c9cac)
![2024-10-01_16 22 32](https://github.com/user-attachments/assets/a53dd62e-652e-44f1-97bf-24205023d582)
![2024-10-01_16 22 46](https://github.com/user-attachments/assets/7195e415-acc3-474a-a9ac-ee9c4b065e23)

**Comment by KasumiNova** [comment]
没有办法复现，我这里是没有问题的。
你确认过你下载的模组是从 CurseForge 上的？
![图片](https://github.com/user-attachments/assets/b0c22a8b-a98d-42e2-a430-a271dcb1edca)
![图片](https://github.com/user-attachments/assets/318a4fb8-c17f-4c40-aa79-bfa5489d67a0)

**Comment by KasumiNova** [comment]
与 CensoredASM 下的所有分支模组不兼容，此问题不考虑修复。
请删除 BlahajASM 并替换为原模组。
