### ISSUE TITLE
越肩视角冲突

### ISSUE THREAD

**Issue by al-wei** [NovaEngineering-Source/StellarCore#16]
星核配置
            # (Client Performance | Experimental) A feature from Patcher mod, using protocol CC-BY-NC-SA 4.0, if there are any copyright issues, please contact me to remove it.
            # Dramatically improves performance by limiting the HUD to a specified FPS, may not be compatible with older devices.
            # May perform strangely with some HUD Mods.
            B:HudCaching=true

            # Select a restricted HUD FPS that is only valid when HudCaching is enabled.
            # Min: 5
            # Max: 240
            I:HudCachingFPSLimit=20

shouldersurfing配置
    # Crosshair type to use for shoulder surfing.
    S:"Crosshair type"=DYNAMIC

这与其动态准星指针的功能开启后，会让界面不停闪烁、抽搐。主要应该是因为动态。
当然越肩视角的动态准星还是有用的，关闭而适应的话有点失落感，希望可用兼容修复。
https://mclo.gs/qdlMg3q

**Comment by al-wei** [comment]
https://github.com/user-attachments/assets/ee180948-09eb-4621-b2ef-576cc4c8bd96

**Comment by KasumiNova** [comment]
这个功能暂时不考虑兼容其他模组，建议关闭即可。
