### ISSUE TITLE
1.5.4及以上版本星核在cleanroom加载器下崩溃

### ISSUE THREAD

**Issue by Candy-sky** [NovaEngineering-Source/StellarCore#17]
我在自用的服务端配套客户端当中尝试使用星核1.5.4及以上（更低的版本我未测试）版本时会发生无法找到“void javax.vecmath.Matrix4f”导致客户端崩溃，使用的Java版本从Java21到Java23均尝试，开发版本从Java官方到zulu Java均尝试，结果为相同报错。
神奇的是，出现此报错的情况均为游戏在后台运行时，意为无论其他条件如何变动，只要游戏处于后台时，加载游戏文件的过程，则必定复现此问题。
如果尝试将游戏放在前台并点击游戏窗口后，期间不做任何操作，等待游戏加载完成，则此问题无法复现。
[2024-10-20-6.log](https://github.com/user-attachments/files/17454826/2024-10-20-6.log)

**Comment by KasumiNova** [comment]
实在邪门

**Comment by KasumiNova** [comment]
最新的提交中是否还有这个问题？

**Comment by Candy-sky** [comment]
最新构建版本#17的测试结果如下
两台分别独立的物理机，使用相同整合包的情况下，一共测试20次打开测试，
其中正常启动次数为5次，主机3次，客机2次，其余均失败，
不同的是，本次即使保持游戏位于前台加载，也会出现崩溃现象，主机客机均有此现象，
日志文件如下
[另一台物理机的日志.zip](https://github.com/user-attachments/files/17477831/default.zip)
[主机日志.zip](https://github.com/user-attachments/files/17477833/default.zip)

**Comment by Candy-sky** [comment]
最新构建版本  修复#17 的测试结果如下
两台分别独立的物理机，一共进行20次打开测试
均已成功启动，此bug无法复现
感谢您的付出
