### ISSUE TITLE
Railcraft introduced and crashed at JEI (HEI)

### ISSUE THREAD

**Issue by tier940** [NovaEngineering-Source/StellarCore#19]
- StellarCore did not crash in the disabled state, so we report it here.
- By the way, the cfg's are all in default.
https://mclo.gs/viwdIJF

**Comment by KasumiNova** [comment]
https://github.com/NovaEngineering-Source/StellarCore/actions/runs/11641751651
Is this problem still present in this version?

**Comment by KasumiNova** [comment]
https://github.com/NovaEngineering-Source/StellarCore/actions/runs/11649768960
Is this problem still present in this version? x 2
