### ISSUE TITLE
新的部分实体（例如拔刀架、植物魔法盖亚、部分生物）会透明隐身，尝试修改Config中ChunkTileEntityMapImprovements选项无法启动

### ISSUE THREAD

**Issue by Not-Angry** [NovaEngineering-Source/StellarCore#2]
在服务器中（1.12.2 catserver最新版本）之前的实体显示无误，但是新创建生成的实体会隐身，例如：拔刀架、召唤的植物魔法的盖亚、部分生物（暂不清楚具体）看不见，但是实际存在，重启之后刀架台可以正常显示了。通过排查模组发现是Stellar-Core的问题，我查看config后发现ChunkTileEntityMapImprovements设置，我尝试通过修改该设置查看是否能够修复，但是设置为false之后会导致服务器无法启动，具体报错如下
[crash-2024-03-26_12.23.22-server.txt](https://github.com/NovaEngineering-Source/StellarCore/files/14752624/crash-2024-03-26_12.23.22-server.txt)
希望大大能够帮忙看看，能否修复或者查看到原因，谢谢！

**Comment by KasumiNova** [comment]
Closed as fixed.
