### ISSUE TITLE
1.5.20 crashes with Resource Hogs

### ISSUE THREAD

**Issue by Radk6** [NovaEngineering-Source/StellarCore#28]
Playing on [an optimized SkyFactory 4 instance](https://github.com/Radk6/MC-Optimization-Guide/blob/main/modpack-specific/1.12.2.md#skyfactory-4) / Cleanroom Loader 0.2.4-alpha, StellarCore 1.5.20

Log: https://mclo.gs/9STqJbF

StellarCore 1.5.13 works fine, same as launching the game with 1.5.13 and then updating to 1.5.20.

**Comment by KasumiNova** [comment]
Disable vintagefix option `vintagefix.mixin.dynamic_resources` due to incompatibility with a Vintagefix feature.
Or disable ParallelModelLoader in StellarCore.

**Comment by Radk6** [comment]
I'm not sure if that was the issue but it doesn't seem to happen with 1.5.21.
