### ISSUE TITLE
HUDFramebuffer 导致字体过度变化

### ISSUE THREAD

**Issue by al-wei** [NovaEngineering-Source/StellarCore#3]
HUDFramebuffer 导致 0.5 字体变小
IGI 字体比例 0.5 变得更小（因为觉得默认1.0太大所以用了0.5）

变化
![image](https://github.com/NovaEngineering-Source/StellarCore/assets/145486869/408c5c67-7726-4f6b-8e27-d7e75ec7528e)
正常
![image](https://github.com/NovaEngineering-Source/StellarCore/assets/145486869/fe11b7a6-1586-4bd8-bde7-ab434e9f8d2f)

![image](https://github.com/NovaEngineering-Source/StellarCore/assets/145486869/39583f1a-a813-4dda-b36a-f3d9a70fc3c0)

**Comment by KasumiNova** [comment]
神秘

**Comment by KasumiNova** [comment]
星核版本？

**Comment by al-wei** [comment]
> 星核版本？

不是只有一个版本吗
![image](https://github.com/NovaEngineering-Source/StellarCore/assets/145486869/bb851d33-422e-4929-af3b-3017bed38ba4)

**Comment by KasumiNova** [comment]
Github 上的已经很久没有更新了，最近只在 mcmod 页面更新。

**Comment by al-wei** [comment]
> Github 上的已经很久没有更新了，最近只在 mcmod 页面更新。

哦！这样，可以了，1.0.3正常显示，能不能上传curseforge啊，也方便包含整合包内。

**Comment by KasumiNova** [comment]
等我做完国际化...
