### ISSUE TITLE
通量网络能否禁止跨世界传输电量

### ISSUE THREAD

**Issue by zfms4188** [NovaEngineering-Source/StellarCore#4]
如题. (或配置传输距离?
不过通量网络的数据是存在world的data里的 大概很麻烦 (

**Comment by KasumiNova** [comment]
作用？

**Comment by zfms4188** [comment]
> 作用？

服务器时,禁止玩家跨世界分享电给其他玩家； 电量数据保存在每个世界的存档位置,可以跨服加载世界保留数据,例如跨服家园世界功能

**Comment by KasumiNova** [comment]
🤔

**Comment by KasumiNova** [comment]
https://github.com/SettingDust/DustyDataSync

**Comment by zfms4188** [comment]
> https://github.com/SettingDust/DustyDataSync

哦！看起来像可以跨服同步了？ 不过这可可以限制分享电吗？

**Comment by KasumiNova** [comment]
暂不考虑此功能，用户范围太小。
